// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdPyhVs8WlvOCptCvB4H741yTY7dV86Rc',
    appId: '1:1030595332077:web:409960d1ac5356f17c09e4',
    messagingSenderId: '1030595332077',
    projectId: 'ormee-98d80',
    authDomain: 'ormee-98d80.firebaseapp.com',
    storageBucket: 'ormee-98d80.firebasestorage.app',
    measurementId: 'G-BGH8087LQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk0R_EW45C-p5DXHEosM2Ym_e0g2NRc1Y',
    appId: '1:1030595332077:android:93fc3e0a4a508ebb7c09e4',
    messagingSenderId: '1030595332077',
    projectId: 'ormee-98d80',
    storageBucket: 'ormee-98d80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdAxZXGaazy7g3PQSzJDyA7Vg6I6fZlzA',
    appId: '1:1030595332077:ios:b9643057727b41a97c09e4',
    messagingSenderId: '1030595332077',
    projectId: 'ormee-98d80',
    storageBucket: 'ormee-98d80.firebasestorage.app',
    iosBundleId: 'com.example.ormeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdAxZXGaazy7g3PQSzJDyA7Vg6I6fZlzA',
    appId: '1:1030595332077:ios:b9643057727b41a97c09e4',
    messagingSenderId: '1030595332077',
    projectId: 'ormee-98d80',
    storageBucket: 'ormee-98d80.firebasestorage.app',
    iosBundleId: 'com.example.ormeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdPyhVs8WlvOCptCvB4H741yTY7dV86Rc',
    appId: '1:1030595332077:web:793a61c38f8cdc007c09e4',
    messagingSenderId: '1030595332077',
    projectId: 'ormee-98d80',
    authDomain: 'ormee-98d80.firebaseapp.com',
    storageBucket: 'ormee-98d80.firebasestorage.app',
    measurementId: 'G-9K88GYLN20',
  );
}
